let selectedActivity='running';
const activityLabels={running:'Joggen',walking:'Gehen',cycling:'Radfahren',hiking:'Wandern',swimming:'Schwimmen',rowing:'Rudern',other:'Freies Training'};
function selectActivity(type){selectedActivity=activityLabels[type]?type:'other';document.querySelectorAll('#activityTypes button').forEach(item=>item.classList.toggle('active',item.dataset.activity===selectedActivity));updateActivityCalories();}
function activityValues(){const raw=Number(document.getElementById('activityMinutes').value),minutes=Number.isFinite(raw)&&raw>=1&&raw<=1440?raw:0,distance=Math.max(0,Number(document.getElementById('activityDistance').value)||0),effort=Number(document.getElementById('activityEffort').value),profile=calorieProfile();return {minutes,distance,effort,profile,calories:estimateCalories({activity:selectedActivity,effort,minutes,profile})};}
function updateActivityCalories(){const values=activityValues();document.getElementById('activityCalories').textContent=`${values.calories} kcal`;document.getElementById('activityEffortValue').textContent=`${values.effort} / 10`;document.getElementById('activityProfileHint').textContent=`${I18n.translate('Berechnet mit')} ${values.profile.weight} kg, ${values.profile.age} ${I18n.translate('Jahren und')} ${values.profile.height} cm.`;}
function renderActivityTemplates(){const templates=data.activityTemplates||[],select=document.getElementById('activityTemplateSelect'),shortcuts=document.getElementById('activityTemplateShortcuts'),card=document.getElementById('activityTemplatesCard'),chosen=select.value;select.replaceChildren(new Option(I18n.translate('Neue Einheit'),''));shortcuts.replaceChildren();card.style.display=templates.length?'':'none';for(const template of templates){select.add(new Option(template.name,template.id));const button=document.createElement('button');button.textContent=`⚡ ${template.name}`;button.onclick=()=>openActivityModal(template.id);shortcuts.append(button);}if(templates.some(item=>item.id===chosen))select.value=chosen;}
function openActivityModal(templateId=''){renderActivityTemplates();document.getElementById('activityMinutes').value=30;document.getElementById('activityDistance').value='';document.getElementById('activityNote').value='';document.getElementById('activityEffort').value=5;document.getElementById('activityTemplateName').value='';selectActivity('running');document.getElementById('activityModal').style.display='flex';if(templateId)applyActivityTemplate(templateId);else updateActivityCalories();}
function closeActivityModal(){document.getElementById('activityModal').style.display='none';}
function applyActivityTemplate(id){const template=(data.activityTemplates||[]).find(item=>item.id===id);document.getElementById('activityTemplateSelect').value=template?id:'';if(!template)return;selectActivity(template.activity);document.getElementById('activityMinutes').value=template.minutes;document.getElementById('activityDistance').value=template.distance||'';document.getElementById('activityEffort').value=template.effort||5;document.getElementById('activityNote').value=template.note||'';document.getElementById('activityTemplateName').value=template.name;updateActivityCalories();}
async function saveActivityTemplate(){const name=document.getElementById('activityTemplateName').value.trim(),values=activityValues();if(!name||!values.minutes){toast(I18n.translate('Bitte gib einen Vorlagennamen und eine Dauer ein.'));return;}data.activityTemplates||=[];const selected=document.getElementById('activityTemplateSelect').value,old=data.activityTemplates.find(item=>item.id===selected);if(!old&&data.activityTemplates.length>=20){toast(I18n.translate('Maximal 20 Vorlagen möglich.'));return;}const template={id:old?.id||`a_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,name:name.slice(0,40),activity:selectedActivity,minutes:values.minutes,distance:values.distance,effort:values.effort,note:document.getElementById('activityNote').value.trim().slice(0,120)};if(old)Object.assign(old,template);else data.activityTemplates.push(template);await saveData();renderActivityTemplates();document.getElementById('activityTemplateSelect').value=template.id;toast(I18n.translate('Vorlage gespeichert.'));}
async function removeActivityTemplate(){const id=document.getElementById('activityTemplateSelect').value;if(!id)return;data.activityTemplates=data.activityTemplates.filter(item=>item.id!==id);await saveData();renderActivityTemplates();document.getElementById('activityTemplateSelect').value='';document.getElementById('activityTemplateName').value='';toast(I18n.translate('Vorlage entfernt.'));}
async function saveFreeActivity(){const {minutes,distance,effort,calories}=activityValues(),name=activityLabels[selectedActivity],note=document.getElementById('activityNote').value.trim();if(!minutes){toast(I18n.translate('Bitte gib eine Dauer ein.'));return;}const detail=distance?`${distance.toLocaleString(I18n.locale())} km`:`${effort} / 10`;data.logs.push({date:new Date().toISOString(),type:'activity',activity:selectedActivity,plan:name,focus:I18n.translate('Freies Training'),sets:0,minutes,calories,distance,effort,note,entries:[{name,weight:0,reps:detail,calories}]});addXP(50,'Training beendet!');await saveData();ForgeSocial.syncProgress();checkMilestones();closeActivityModal();renderHome();toast(I18n.translate('Freies Training gespeichert.'));}
document.querySelectorAll('#activityTypes button').forEach(button=>button.addEventListener('click',()=>selectActivity(button.dataset.activity)));
for(const id of ['activityMinutes','activityDistance','activityEffort'])document.getElementById(id).addEventListener('input',updateActivityCalories);
window.addEventListener('forge-language-change',()=>{renderActivityTemplates();if(document.getElementById('activityModal').style.display==='flex')updateActivityCalories();});
