const I18n = (() => {
  const languages = ['de','en','el'];
  const en = {
    'Konto wird geladen …':'Loading account …','Home':'Home','Woche':'Week','Pläne':'Plans','Statistik':'Statistics','Trophäen':'Trophies','📅 Woche':'📅 Week','📚 Pläne':'📚 Plans','📈 Statistik':'📈 Statistics','🏆 Trophäen':'🏆 Trophies','Konto und Freunde':'Account and friends',
    'Gespeichertes Training':'Saved workout','Training fortsetzen':'Continue workout','FORTSETZEN':'CONTINUE','Verwerfen':'Discard','Wochenziel':'Weekly goal','Regenerationstag - Erhalte deinen Streak automatisch aufrecht!':'Recovery day – keep your streak automatically!','HEUTE':'TODAY','Level':'Level',
    'TRAINING STARTEN':'START WORKOUT','Dein Überblick':'Your overview','Trainings':'Workouts','Sätze':'Sets','Minuten':'Minutes','Rekorde':'Records','Nächstes':'Next','Diese Woche':'This week',
    'Aktueller Plan':'Current plan','✏️ Bearbeiten':'✏️ Edit','Meine Pläne':'My plans','🌐 Entdecken':'🌐 Discover','👥 Freunde':'👥 Friends','➕ Neuer Plan':'➕ New plan','🤖 KI-Plan erstellen':'🤖 Create AI plan',
    'Entdecke veröffentlichte Pläne. Du kannst sie ansehen oder als eigene Kopie auswählen und sofort damit trainieren.':'Discover published plans. Preview them or choose your own copy and start training immediately.',
    'Vorschau':'Preview','Auswählen':'Choose','Melde dich an, um geteilte Pläne zu sehen.':'Sign in to see shared plans.','📊 Übungs-Verlauf':'📊 Exercise history','Wähle Übung...':'Choose exercise...',
    'Verfolge dein Volumen & Maximalgewicht pro Übung.':'Track volume and maximum weight for each exercise.','⚖️ Körperdaten':'⚖️ Body data','Gewicht (kg)':'Weight (kg)','Körperfett (%)':'Body fat (%)','Brust (cm)':'Chest (cm)','Bauch (cm)':'Waist (cm)','Arme (cm)':'Arms (cm)','Beine (cm)':'Legs (cm)','+ Messung eintragen':'+ Add measurement',
    '📜 Trainings-Historie':'📜 Workout history','Klicke auf ein Training für Details.':'Tap a workout for details.','🔥 Meilensteine':'🔥 Milestones','Erreiche Ziele, um Bonus-XP zu sammeln!':'Reach goals to earn bonus XP!','⭐ XP Protokoll':'⭐ XP log','Deine zuletzt verdienten Erfahrungspunkte.':'Your latest experience points.',
    'Aufwärmen vor dem Training':'Warm-up before training','AUFWÄRMEN BEENDEN & WEITER':'FINISH WARM-UP & CONTINUE','SATZ ABSCHLIESSEN':'FINISH SET','ÜBERSPRINGEN':'SKIP','↩️ Zurück':'↩️ Undo','Pause':'Rest','PAUSE BEENDEN & WEITER':'END REST & CONTINUE','Beenden & speichern':'Stop & save','⛶ Vollbild':'⛶ Full screen','TRAINING COMPLETE':'WORKOUT COMPLETE','ZURÜCK ZU FORGE':'BACK TO FORGE',
    '🏋️ 1RM Rechner':'🏋️ 1RM calculator','Berechne dein geschätztes One Rep Max.':'Calculate your estimated one rep max.','Wiederholungen':'Repetitions','Dein geschätztes 1 Rep Max:':'Your estimated 1 rep max:','✏️ Plan bearbeiten':'✏️ Edit plan','Plan Name':'Plan name','+ Übung / Cardio hinzufügen':'+ Add exercise / cardio','PLAN SPEICHERN':'SAVE PLAN','Abbrechen':'Cancel',
    '🤖 KI Plan erstellen':'🤖 Create AI plan','PROMPT GENERIEREN':'GENERATE PROMPT','📋 Prompt kopieren':'📋 Copy prompt','PLAN ERSTELLEN':'CREATE PLAN','Plan Vorschau':'Plan preview','📲 FORGE installieren':'📲 Install FORGE','LINK KOPIEREN':'COPY LINK','FERTIG':'DONE',
    'Info':'Info','Verstanden':'Got it','Training':'Workout','⚙️ Einstellungen':'⚙️ Settings','App':'App','Sprache':'Language','Training':'Training','Gewichtseinheit':'Weight unit','Kilogramm (kg)':'Kilograms (kg)','Pfund (lb)':'Pounds (lb)','Trainingsziel pro Woche':'Weekly workout goal','Standard-Pause (Sekunden)':'Default rest (seconds)','Pausen Quick-Buttons (Kommagetrennt in Sek.)':'Quick rest buttons (seconds, comma-separated)','Vor dem Training aufwärmen?':'Warm up before training?','Nein':'No','Ja':'Yes','Welches Aufwärmen?':'Warm-up type','Dynamisches Dehnen':'Dynamic stretching','Seilspringen':'Jump rope',
    'Während des Trainings':'During workout','Display aktiv halten':'Keep screen on','Verhindert nach Möglichkeit, dass der Bildschirm ausgeht.':'Prevents the screen from turning off when supported.','Bei Pausenende vibrieren':'Vibrate when rest ends','Funktioniert auf unterstützten Smartphones.':'Works on supported phones.','Signalton bei Pausenende':'Sound when rest ends','Spielt einen kurzen, dezenten Ton ab.':'Plays a short, subtle sound.','SPEICHERN':'SAVE','💾 Export':'💾 Export','📥 Import':'📥 Import','Daten löschen':'Delete data',
    'Willkommen bei FORGE':'Welcome to FORGE','Dein FORGE-Konto':'Your FORGE account','Dein Training. Dein Fortschritt. Auf deinen Geräten.':'Your training. Your progress. On all your devices.','Anmelden':'Sign in','Registrieren':'Register','Konto':'Account','Benutzername (für Freunde sichtbar)':'Username (visible to friends)','Jeder Benutzername kann nur einmal verwendet werden.':'Each username can only be used once.','E-Mail-Adresse':'Email address','Passwort':'Password','ANMELDEN':'SIGN IN','KONTO ERSTELLEN':'CREATE ACCOUNT','OHNE KONTO LOKAL TRAINIEREN':'TRAIN LOCALLY WITHOUT ACCOUNT','📲 App installieren':'📲 Install app','Mit Konto werden deine Pläne, Trainings, Körperdaten und Einstellungen privat in Supabase (Frankfurt) gespeichert. Freunde sehen nur deinen Anzeigenamen. Eine E-Mail-Bestätigung ist derzeit nicht nötig. Auf diesem Gerät bleibt eine Offline-Kopie.':'With an account, your plans, workouts, body data and settings are stored privately in Supabase (Frankfurt). Friends only see your username. Email confirmation is currently not required. An offline copy remains on this device.','Vorhandene Daten aus deiner bisherigen FORGE-Version kannst du nach dem Anmelden über Einstellungen → Import übernehmen.':'After signing in, you can import data from your previous FORGE version through Settings → Import.',
    '👤 Konto & Freunde':'👤 Account & friends','Jetzt synchronisieren':'Sync now','Lokale Gastdaten übernehmen':'Import local guest data','Abmelden':'Sign out','Zwei verschiedene Datenstände':'Two different data versions','Cloud-Stand übernehmen':'Use cloud version','Diesen Gerätestand verwenden':'Use this device version','Dein Anzeigename':'Your username','Speichern':'Save','Dein Freundescode':'Your friend code','Teile diesen Code nur mit Personen, die dich hinzufügen dürfen.':'Only share this code with people allowed to add you.','Code kopieren':'Copy code','Freunde':'Friends','Kontakte sehen nur deinen Anzeigenamen. Trainings- und Körperdaten werden nicht geteilt.':'Contacts only see your username. Workout and body data are not shared.','Freundescode einfügen':'Enter friend code','Freundescode':'Friend code','Anfragen':'Request','Aktualisieren':'Refresh','Wochen-Challenges':'Weekly challenges','Teile nur den Fortschritt dieser Challenge, keine Trainingsdetails.':'Only share challenge progress, never workout details.','Starten':'Start',
    'Konto löschen':'Delete account','Dein Konto und alle damit gespeicherten Daten werden dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.':'Your account and all stored data will be permanently deleted. This cannot be undone.','KONTO DAUERHAFT LÖSCHEN':'DELETE ACCOUNT PERMANENTLY',
    '👥 Plan teilen':'👥 Share plan','Freund auswählen':'Choose friend','Der Empfänger erhält eine unabhängige Kopie. Spätere Änderungen werden nicht automatisch geteilt.':'The recipient gets an independent copy. Later changes are not shared automatically.','PLAN SENDEN':'SEND PLAN',
    'Dieser Benutzername ist bereits vergeben.':'This username is already taken.','Bitte gib einen Benutzernamen mit 1–40 Zeichen ein.':'Enter a username with 1–40 characters.','Benutzername gespeichert.':'Username saved.','Konto wird gelöscht …':'Deleting account …','Konto gelöscht':'Account deleted','Dein Konto und die gespeicherten Daten wurden gelöscht.':'Your account and stored data were deleted.','Konto jetzt endgültig löschen? Diese Aktion kann nicht rückgängig gemacht werden.':'Delete the account permanently now? This cannot be undone.',
    'Bitte warten …':'Please wait …','E-Mail oder Passwort stimmt nicht.':'Email or password is incorrect.','Keine Verbindung. Deine lokal gespeicherten Trainingsdaten bleiben erhalten.':'No connection. Your locally saved workout data remain available.','In der Cloud gespeichert':'Saved in the cloud','Nur auf diesem Gerät':'Only on this device','Abgemeldet':'Signed out','Gespeichert.':'Saved.','Noch keine Kontakte. Tausche deinen Freundescode persönlich aus.':'No contacts yet. Exchange your friend code in person.','Befreundet':'Friends','Anfrage erhalten':'Request received','Anfrage gesendet':'Request sent','Annehmen':'Accept','Entfernen':'Remove','Ablehnen':'Decline','Zurückziehen':'Withdraw',
    'Einstellungen gespeichert':'Settings saved','Synchronisiert.':'Synced.','Noch nicht synchronisiert. Prüfe Verbindung oder Versionskonflikt.':'Not synced yet. Check the connection or resolve the version conflict.','Name gespeichert.':'Name saved.','Montag':'Monday','Dienstag':'Tuesday','Mittwoch':'Wednesday','Donnerstag':'Thursday','Freitag':'Friday','Samstag':'Saturday','Sonntag':'Sunday','Regeneration':'Recovery','Mein erster Plan':'My first plan','Heute':'Today','Ruhetag':'Rest day'
  };
  const el = {
    'Konto wird geladen …':'Φόρτωση λογαριασμού …','Home':'Αρχική','Woche':'Εβδομάδα','Pläne':'Πλάνα','Statistik':'Στατιστικά','Trophäen':'Τρόπαια','🏠 Home':'🏠 Αρχική','📅 Woche':'📅 Εβδομάδα','📚 Pläne':'📚 Πλάνα','📈 Statistik':'📈 Στατιστικά','🏆 Trophäen':'🏆 Τρόπαια','Konto und Freunde':'Λογαριασμός και φίλοι',
    'Gespeichertes Training':'Αποθηκευμένη προπόνηση','Training fortsetzen':'Συνέχιση προπόνησης','FORTSETZEN':'ΣΥΝΕΧΕΙΑ','Verwerfen':'Απόρριψη','Wochenziel':'Εβδομαδιαίος στόχος','Regenerationstag - Erhalte deinen Streak automatisch aufrecht!':'Ημέρα αποκατάστασης – διατήρησε αυτόματα το σερί σου!','HEUTE':'ΣΗΜΕΡΑ','Level':'Επίπεδο','TRAINING STARTEN':'ΕΝΑΡΞΗ ΠΡΟΠΟΝΗΣΗΣ','Dein Überblick':'Η επισκόπησή σου','Trainings':'Προπονήσεις','Sätze':'Σετ','Minuten':'Λεπτά','Rekorde':'Ρεκόρ','Nächstes':'Επόμενο','Diese Woche':'Αυτή την εβδομάδα',
    'Aktueller Plan':'Τρέχον πλάνο','✏️ Bearbeiten':'✏️ Επεξεργασία','Meine Pläne':'Τα πλάνα μου','🌐 Entdecken':'🌐 Ανακάλυψη','👥 Freunde':'👥 Φίλοι','➕ Neuer Plan':'➕ Νέο πλάνο','🤖 KI-Plan erstellen':'🤖 Δημιουργία πλάνου AI','Vorschau':'Προεπισκόπηση','Auswählen':'Επιλογή','Melde dich an, um geteilte Pläne zu sehen.':'Συνδέσου για να δεις κοινόχρηστα πλάνα.','📊 Übungs-Verlauf':'📊 Ιστορικό ασκήσεων','Wähle Übung...':'Επίλεξε άσκηση...','Verfolge dein Volumen & Maximalgewicht pro Übung.':'Παρακολούθησε τον όγκο και το μέγιστο βάρος κάθε άσκησης.',
    '⚖️ Körperdaten':'⚖️ Στοιχεία σώματος','Gewicht (kg)':'Βάρος (kg)','Körperfett (%)':'Σωματικό λίπος (%)','Brust (cm)':'Στήθος (cm)','Bauch (cm)':'Μέση (cm)','Arme (cm)':'Χέρια (cm)','Beine (cm)':'Πόδια (cm)','+ Messung eintragen':'+ Προσθήκη μέτρησης','📜 Trainings-Historie':'📜 Ιστορικό προπονήσεων','Klicke auf ein Training für Details.':'Πάτησε σε μια προπόνηση για λεπτομέρειες.','🔥 Meilensteine':'🔥 Ορόσημα','Erreiche Ziele, um Bonus-XP zu sammeln!':'Πέτυχε στόχους για μπόνους XP!','⭐ XP Protokoll':'⭐ Αρχείο XP','Deine zuletzt verdienten Erfahrungspunkte.':'Οι τελευταίοι πόντοι εμπειρίας σου.',
    'Aufwärmen vor dem Training':'Προθέρμανση πριν την προπόνηση','AUFWÄRMEN BEENDEN & WEITER':'ΤΕΛΟΣ ΠΡΟΘΕΡΜΑΝΣΗΣ & ΣΥΝΕΧΕΙΑ','SATZ ABSCHLIESSEN':'ΟΛΟΚΛΗΡΩΣΗ ΣΕΤ','ÜBERSPRINGEN':'ΠΑΡΑΛΕΙΨΗ','↩️ Zurück':'↩️ Αναίρεση','Pause':'Διάλειμμα','PAUSE BEENDEN & WEITER':'ΤΕΛΟΣ ΔΙΑΛΕΙΜΜΑΤΟΣ & ΣΥΝΕΧΕΙΑ','Beenden & speichern':'Τέλος & αποθήκευση','⛶ Vollbild':'⛶ Πλήρης οθόνη','TRAINING COMPLETE':'Η ΠΡΟΠΟΝΗΣΗ ΟΛΟΚΛΗΡΩΘΗΚΕ','ZURÜCK ZU FORGE':'ΠΙΣΩ ΣΤΟ FORGE',
    '🏋️ 1RM Rechner':'🏋️ Υπολογιστής 1RM','Berechne dein geschätztes One Rep Max.':'Υπολόγισε το εκτιμώμενο μέγιστο μιας επανάληψης.','Wiederholungen':'Επαναλήψεις','Dein geschätztes 1 Rep Max:':'Εκτιμώμενο 1RM:','✏️ Plan bearbeiten':'✏️ Επεξεργασία πλάνου','Plan Name':'Όνομα πλάνου','+ Übung / Cardio hinzufügen':'+ Προσθήκη άσκησης / cardio','PLAN SPEICHERN':'ΑΠΟΘΗΚΕΥΣΗ ΠΛΑΝΟΥ','Abbrechen':'Ακύρωση','Plan Vorschau':'Προεπισκόπηση πλάνου','📲 FORGE installieren':'📲 Εγκατάσταση FORGE','LINK KOPIEREN':'ΑΝΤΙΓΡΑΦΗ ΣΥΝΔΕΣΜΟΥ','FERTIG':'ΤΕΛΟΣ',
    'Info':'Πληροφορίες','Verstanden':'Κατάλαβα','Training':'Προπόνηση','⚙️ Einstellungen':'⚙️ Ρυθμίσεις','App':'Εφαρμογή','Sprache':'Γλώσσα','Gewichtseinheit':'Μονάδα βάρους','Kilogramm (kg)':'Κιλά (kg)','Pfund (lb)':'Λίβρες (lb)','Trainingsziel pro Woche':'Στόχος προπονήσεων ανά εβδομάδα','Standard-Pause (Sekunden)':'Τυπικό διάλειμμα (δευτερόλεπτα)','Pausen Quick-Buttons (Kommagetrennt in Sek.)':'Γρήγορα διαλείμματα (δευτ., με κόμμα)','Vor dem Training aufwärmen?':'Προθέρμανση πριν την προπόνηση;','Nein':'Όχι','Ja':'Ναι','Welches Aufwärmen?':'Τύπος προθέρμανσης','Dynamisches Dehnen':'Δυναμικές διατάσεις','Seilspringen':'Σχοινάκι',
    'Während des Trainings':'Κατά την προπόνηση','Display aktiv halten':'Διατήρηση οθόνης ενεργής','Verhindert nach Möglichkeit, dass der Bildschirm ausgeht.':'Αποτρέπει το σβήσιμο της οθόνης όπου υποστηρίζεται.','Bei Pausenende vibrieren':'Δόνηση στο τέλος διαλείμματος','Funktioniert auf unterstützten Smartphones.':'Λειτουργεί σε υποστηριζόμενα κινητά.','Signalton bei Pausenende':'Ήχος στο τέλος διαλείμματος','Spielt einen kurzen, dezenten Ton ab.':'Παίζει έναν σύντομο διακριτικό ήχο.','SPEICHERN':'ΑΠΟΘΗΚΕΥΣΗ','💾 Export':'💾 Εξαγωγή','📥 Import':'📥 Εισαγωγή','Daten löschen':'Διαγραφή δεδομένων',
    'Willkommen bei FORGE':'Καλώς ήρθες στο FORGE','Dein FORGE-Konto':'Ο λογαριασμός σου FORGE','Dein Training. Dein Fortschritt. Auf deinen Geräten.':'Η προπόνησή σου. Η πρόοδός σου. Σε όλες τις συσκευές σου.','Anmelden':'Σύνδεση','Registrieren':'Εγγραφή','Konto':'Λογαριασμός','Benutzername (für Freunde sichtbar)':'Όνομα χρήστη (ορατό στους φίλους)','Jeder Benutzername kann nur einmal verwendet werden.':'Κάθε όνομα χρήστη μπορεί να χρησιμοποιηθεί μόνο μία φορά.','E-Mail-Adresse':'Email','Passwort':'Κωδικός','ANMELDEN':'ΣΥΝΔΕΣΗ','KONTO ERSTELLEN':'ΔΗΜΙΟΥΡΓΙΑ ΛΟΓΑΡΙΑΣΜΟΥ','OHNE KONTO LOKAL TRAINIEREN':'ΤΟΠΙΚΗ ΠΡΟΠΟΝΗΣΗ ΧΩΡΙΣ ΛΟΓΑΡΙΑΣΜΟ','📲 App installieren':'📲 Εγκατάσταση εφαρμογής','Mit Konto werden deine Pläne, Trainings, Körperdaten und Einstellungen privat in Supabase (Frankfurt) gespeichert. Freunde sehen nur deinen Anzeigenamen. Eine E-Mail-Bestätigung ist derzeit nicht nötig. Auf diesem Gerät bleibt eine Offline-Kopie.':'Με λογαριασμό, τα πλάνα, οι προπονήσεις, τα στοιχεία σώματος και οι ρυθμίσεις αποθηκεύονται ιδιωτικά στο Supabase (Φρανκφούρτη). Οι φίλοι βλέπουν μόνο το όνομα χρήστη. Δεν απαιτείται προς το παρόν επιβεβαίωση email. Ένα αντίγραφο παραμένει στη συσκευή.','Vorhandene Daten aus deiner bisherigen FORGE-Version kannst du nach dem Anmelden über Einstellungen → Import übernehmen.':'Μετά τη σύνδεση μπορείς να εισαγάγεις δεδομένα από την προηγούμενη έκδοση FORGE μέσω Ρυθμίσεις → Εισαγωγή.',
    '👤 Konto & Freunde':'👤 Λογαριασμός & φίλοι','Jetzt synchronisieren':'Συγχρονισμός τώρα','Lokale Gastdaten übernehmen':'Εισαγωγή τοπικών δεδομένων επισκέπτη','Abmelden':'Αποσύνδεση','Zwei verschiedene Datenstände':'Δύο διαφορετικές εκδόσεις δεδομένων','Cloud-Stand übernehmen':'Χρήση έκδοσης cloud','Diesen Gerätestand verwenden':'Χρήση έκδοσης συσκευής','Dein Anzeigename':'Το όνομα χρήστη σου','Speichern':'Αποθήκευση','Dein Freundescode':'Ο κωδικός φίλου σου','Teile diesen Code nur mit Personen, die dich hinzufügen dürfen.':'Μοιράσου τον κωδικό μόνο με άτομα που επιτρέπεται να σε προσθέσουν.','Code kopieren':'Αντιγραφή κωδικού','Freunde':'Φίλοι','Kontakte sehen nur deinen Anzeigenamen. Trainings- und Körperdaten werden nicht geteilt.':'Οι επαφές βλέπουν μόνο το όνομα χρήστη. Τα δεδομένα προπόνησης και σώματος δεν κοινοποιούνται.','Freundescode einfügen':'Εισαγωγή κωδικού φίλου','Freundescode':'Κωδικός φίλου','Anfragen':'Αίτημα','Aktualisieren':'Ανανέωση','Wochen-Challenges':'Εβδομαδιαίες προκλήσεις','Teile nur den Fortschritt dieser Challenge, keine Trainingsdetails.':'Κοινοποίησε μόνο την πρόοδο της πρόκλησης, όχι λεπτομέρειες προπόνησης.','Starten':'Έναρξη',
    'Konto löschen':'Διαγραφή λογαριασμού','Dein Konto und alle damit gespeicherten Daten werden dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.':'Ο λογαριασμός και όλα τα αποθηκευμένα δεδομένα θα διαγραφούν οριστικά. Η ενέργεια δεν αναιρείται.','KONTO DAUERHAFT LÖSCHEN':'ΟΡΙΣΤΙΚΗ ΔΙΑΓΡΑΦΗ ΛΟΓΑΡΙΑΣΜΟΥ','👥 Plan teilen':'👥 Κοινοποίηση πλάνου','Freund auswählen':'Επιλογή φίλου','PLAN SENDEN':'ΑΠΟΣΤΟΛΗ ΠΛΑΝΟΥ',
    'Dieser Benutzername ist bereits vergeben.':'Αυτό το όνομα χρήστη χρησιμοποιείται ήδη.','Bitte gib einen Benutzernamen mit 1–40 Zeichen ein.':'Δώσε όνομα χρήστη 1–40 χαρακτήρων.','Benutzername gespeichert.':'Το όνομα χρήστη αποθηκεύτηκε.','Konto wird gelöscht …':'Διαγραφή λογαριασμού …','Konto gelöscht':'Ο λογαριασμός διαγράφηκε','Dein Konto und die gespeicherten Daten wurden gelöscht.':'Ο λογαριασμός και τα δεδομένα διαγράφηκαν.','Konto jetzt endgültig löschen? Diese Aktion kann nicht rückgängig gemacht werden.':'Να διαγραφεί οριστικά ο λογαριασμός; Η ενέργεια δεν αναιρείται.',
    'Bitte warten …':'Περίμενε …','E-Mail oder Passwort stimmt nicht.':'Το email ή ο κωδικός είναι λάθος.','In der Cloud gespeichert':'Αποθηκεύτηκε στο cloud','Nur auf diesem Gerät':'Μόνο σε αυτή τη συσκευή','Abgemeldet':'Αποσυνδέθηκε','Gespeichert.':'Αποθηκεύτηκε.','Noch keine Kontakte. Tausche deinen Freundescode persönlich aus.':'Δεν υπάρχουν επαφές ακόμη. Αντάλλαξε προσωπικά τον κωδικό φίλου.','Befreundet':'Φίλοι','Anfrage erhalten':'Λήφθηκε αίτημα','Anfrage gesendet':'Το αίτημα στάλθηκε','Annehmen':'Αποδοχή','Entfernen':'Αφαίρεση','Ablehnen':'Απόρριψη','Zurückziehen':'Ανάκληση','Einstellungen gespeichert':'Οι ρυθμίσεις αποθηκεύτηκαν','Synchronisiert.':'Συγχρονίστηκε.','Montag':'Δευτέρα','Dienstag':'Τρίτη','Mittwoch':'Τετάρτη','Donnerstag':'Πέμπτη','Freitag':'Παρασκευή','Samstag':'Σάββατο','Sonntag':'Κυριακή','Regeneration':'Αποκατάσταση','Mein erster Plan':'Το πρώτο μου πλάνο','Heute':'Σήμερα','Ruhetag':'Ημέρα ξεκούρασης'
  };

  let language = languages.includes(data?.settings?.language) ? data.settings.language : (localStorage.getItem('forgeLanguage') || 'de');
  const originals = new WeakMap();
  const attributeOriginals = new WeakMap();
  let observer;

  function dictionary(){return language==='en'?en:language==='el'?el:null;}
  function translate(raw){
    if(language==='de' || typeof raw!=='string')return raw;
    const dict=dictionary(), trimmed=raw.trim();
    let value=dict[trimmed];
    if(!value){
      let match=trimmed.match(/^(\d+) von (\d+) Trainings$/);
      if(match)value=language==='el'?`${match[1]} από ${match[2]} προπονήσεις`:`${match[1]} of ${match[2]} workouts`;
      match ||= trimmed.match(/^Level (\d+)$/);
      if(!value&&match)value=language==='el'?`Επίπεδο ${match[1]}`:`Level ${match[1]}`;
      const replacements=language==='el'
        ? [['Training fortsetzen','Συνέχιση προπόνησης'],[' Trainings diese Woche',' προπονήσεις αυτή την εβδομάδα'],['Noch keine Challenge in dieser Woche.','Δεν υπάρχει πρόκληση αυτή την εβδομάδα.'],['Übungen','ασκήσεις'],['Übung','άσκηση'],['Sätze','σετ'],['Satz','σετ'],['Pause','Διάλειμμα'],['HEUTE','ΣΗΜΕΡΑ'],['MONTAG','ΔΕΥΤΕΡΑ'],['DIENSTAG','ΤΡΙΤΗ'],['MITTWOCH','ΤΕΤΑΡΤΗ'],['DONNERSTAG','ΠΕΜΠΤΗ'],['FREITAG','ΠΑΡΑΣΚΕΥΗ'],['SAMSTAG','ΣΑΒΒΑΤΟ'],['SONNTAG','ΚΥΡΙΑΚΗ']]
        : [['Training fortsetzen','Continue workout'],[' Trainings diese Woche',' workouts this week'],['Noch keine Challenge in dieser Woche.','No challenge this week.'],['Übungen','exercises'],['Übung','exercise'],['Sätze','sets'],['Satz','set'],['Pause','Rest'],['HEUTE','TODAY'],['MONTAG','MONDAY'],['DIENSTAG','TUESDAY'],['MITTWOCH','WEDNESDAY'],['DONNERSTAG','THURSDAY'],['FREITAG','FRIDAY'],['SAMSTAG','SATURDAY'],['SONNTAG','SUNDAY']];
      if(!value){value=trimmed;for(const [from,to] of replacements)value=value.replace(from,to);if(value===trimmed)value=null;}
    }
    if(!value)return raw;
    return raw.replace(trimmed,value);
  }
  function translateAttribute(element,name){
    let map=attributeOriginals.get(element);if(!map){map={};attributeOriginals.set(element,map);}
    if(!(name in map))map[name]=element.getAttribute(name);
    const next=translate(map[name]);if(next!==element.getAttribute(name))element.setAttribute(name,next);
  }
  function translateNode(node){
    if(node.nodeType===Node.TEXT_NODE){
      if(!node.parentElement || /^(SCRIPT|STYLE|TEXTAREA)$/.test(node.parentElement.tagName))return;
      if(!originals.has(node))originals.set(node,node.nodeValue);
      const next=translate(originals.get(node));if(node.nodeValue!==next)node.nodeValue=next;return;
    }
    if(node.nodeType!==Node.ELEMENT_NODE)return;
    for(const name of ['placeholder','title','aria-label'])if(node.hasAttribute(name))translateAttribute(node,name);
    for(const child of node.childNodes)translateNode(child);
  }
  function apply(){
    observer?.disconnect();document.documentElement.lang=language;translateNode(document.body);
    observer?.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']});
  }
  function setLanguage(next){
    language=languages.includes(next)?next:'de';localStorage.setItem('forgeLanguage',language);
    if(data?.settings)data.settings.language=language;apply();window.dispatchEvent(new CustomEvent('forge-language-change',{detail:{language}}));
  }
  function deleteWord(){return language==='en'?'DELETE':language==='el'?'ΔΙΑΓΡΑΦΗ':'LÖSCHEN';}
  function deletionPrompt(){const word=deleteWord();return language==='en'?`Type ${word} to permanently delete your account and all stored data.`:language==='el'?`Πληκτρολόγησε ${word} για να διαγράψεις οριστικά τον λογαριασμό και όλα τα δεδομένα.`:`Gib ${word} ein, um dein Konto und alle gespeicherten Daten dauerhaft zu löschen.`;}

  const nativeConfirm=window.confirm.bind(window),nativeAlert=window.alert.bind(window),nativePrompt=window.prompt.bind(window);
  window.confirm=text=>nativeConfirm(translate(String(text)));
  window.alert=text=>nativeAlert(translate(String(text)));
  window.prompt=(text,value)=>nativePrompt(translate(String(text)),value);
  observer=new MutationObserver(records=>{observer.disconnect();for(const record of records){if(record.type==='characterData'){originals.set(record.target,record.target.nodeValue);translateNode(record.target);}else if(record.type==='attributes'){const map=attributeOriginals.get(record.target)||{};map[record.attributeName]=record.target.getAttribute(record.attributeName);attributeOriginals.set(record.target,map);translateAttribute(record.target,record.attributeName);}else for(const node of record.addedNodes)translateNode(node);}observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']});});
  apply();
  return {setLanguage,translate,language:()=>language,locale:()=>language==='el'?'el-GR':language==='en'?'en-GB':'de-AT',deleteWord,deletionPrompt};
})();

