const ForgeSocial=(()=>{
  let friends=[],sharingPlanId=null,challengeFilter='active';
  const $=id=>document.getElementById(id),t=value=>I18n.translate(value);
  const metricSettings={workouts:{label:'Trainings',default:3,presets:[3,5,10],max:1000,unit:''},sets:{label:'Sätze',default:50,presets:[25,50,100],max:100000,unit:''},minutes:{label:'Trainingsminuten',default:300,presets:[120,300,600],max:1000000,unit:' min'},calories:{label:'Kalorien',default:1500,presets:[500,1500,3000],max:1000000000,unit:' kcal'},volume:{label:'Bewegtes Gewicht',default:10000,presets:[5000,10000,25000],max:1000000000,unit:' kg'}};
  async function loadFriends(){
    if(!ForgeCloud.isSignedIn()){friends=[];return friends;}friends=await ForgeCloud.social('friends');if($('friendCount'))$('friendCount').textContent=friends.length;
    for(const select of [$('shareFriendSelect'),$('challengeFriend')].filter(Boolean)){const chosen=select.value;select.replaceChildren();if(!friends.length){const o=document.createElement('option');o.textContent=t('Noch keine Freunde');o.value='';select.append(o);continue;}for(const f of friends){const o=document.createElement('option');o.value=f.user_id;o.textContent=f.display_name;select.append(o);}if(friends.some(f=>f.user_id===chosen))select.value=chosen;}return friends;
  }
  async function refreshFriendsPage(){const signed=ForgeCloud.isSignedIn();$('friendsSignedOut')?.classList.toggle('hidden',signed);$('friendsSignedIn')?.classList.toggle('hidden',!signed);if(!signed)return;try{await ForgeCloud.refreshFriends();await loadFriends();await refreshChallenges();}catch(error){if($('challengesList'))$('challengesList').textContent=error.message;}}
  function switchView(view){const people=view==='people';$('friendsPeoplePanel').classList.toggle('hidden',!people);$('friendsChallengesPanel').classList.toggle('hidden',people);$('friendsPeopleTab').classList.toggle('active',people);$('friendsChallengesTab').classList.toggle('active',!people);if(!people)refreshChallenges();}
  function challengeFriend(userId){switchView('challenges');$('challengeFriend').value=userId;toggleComposer(true);$('challengeComposer').scrollIntoView({behavior:'smooth',block:'center'});}
  async function challengeFriendName(name){try{await loadFriends();const match=friends.find(friend=>friend.display_name===name);if(match)challengeFriend(match.user_id);else toast(t('Freund nicht gefunden.'));}catch(error){toast(error.message);}}
  function toggleComposer(force){const composer=$('challengeComposer'),show=typeof force==='boolean'?force:composer.classList.contains('hidden');composer.classList.toggle('hidden',!show);$('challengeComposerToggle').textContent=show?t('Schließen'):t('+ Neue Challenge');}
  async function openShare(planId){if(!ForgeCloud.isSignedIn()){toast(t('Melde dich an, um Pläne zu teilen.'));return;}const plan=data.allPlans.find(p=>p.id===planId);if(!plan)return;try{await loadFriends();if(!friends.length){toast(t('Füge zuerst einen Freund hinzu.'));return;}sharingPlanId=planId;$('sharePlanName').textContent=plan.name;$('sharePlanModal').style.display='flex';}catch(error){toast(error.message);}}
  function closeShare(){$('sharePlanModal').style.display='none';sharingPlanId=null;}
  async function sendShare(){const plan=data.allPlans.find(p=>p.id===sharingPlanId),friend=$('shareFriendSelect').value;if(!plan||!friend)return;$('sharePlanSend').disabled=true;try{await ForgeCloud.social('share_plan',{friend,payload:plan});closeShare();toast(t('Plan gesendet.'));}catch(error){toast(error.message);}finally{$('sharePlanSend').disabled=false;}}
  async function refreshShares(){const list=$('sharedPlansList');if(!list)return;if(!ForgeCloud.isSignedIn()){list.innerHTML=`<div class="sub">${t('Melde dich an, um geteilte Pläne zu sehen.')}</div>`;return;}try{const shares=await ForgeCloud.social('plan_shares');list.replaceChildren();if(!shares.length){list.innerHTML=`<div class="sub">${t('Noch keine geteilten Pläne.')}</div>`;return;}for(const share of shares){const row=document.createElement('div');row.className='record';const text=document.createElement('div'),title=document.createElement('b'),sub=document.createElement('small');title.textContent=share.plan.name||t('Trainingsplan');sub.textContent=`${t('Von')} ${share.sender_name}`;sub.className='sub';text.append(title,sub);const actions=document.createElement('div');actions.className='plan-actions';for(const [label,fn] of [[t('Übernehmen'),()=>takeShare(share.id,share.sender_name)],[t('Ablehnen'),()=>dismissShare(share.id)]]){const b=document.createElement('button');b.className='btn secondary';b.textContent=label;b.onclick=fn;actions.append(b);}row.append(text,actions);list.append(row);}}catch(error){list.textContent=error.message;}}
  async function takeShare(id,sender){try{const plan=await ForgeCloud.social('take_plan',{id});if(!plan||!Array.isArray(plan.days)||plan.days.length!==7)throw Error(t('Der geteilte Plan ist ungültig.'));const copy=JSON.parse(JSON.stringify(plan));copy.id='p_shared_'+Date.now();copy.name=`${copy.name||t('Trainingsplan')} · ${sender}`;copy.archived=false;data.allPlans.push(copy);await saveData();renderPlansList();await refreshShares();toast(t('Plan als eigene Kopie übernommen.'));}catch(error){toast(error.message);}}
  async function dismissShare(id){try{await ForgeCloud.social('dismiss_share',{id});await refreshShares();}catch(error){toast(error.message);}}
  function updateChallengeDefaults(){const config=metricSettings[$('challengeMetric')?.value]||metricSettings.workouts,target=$('challengeTarget');if(!target)return;target.max=config.max;if(!target.dataset.changed)target.value=config.default;const presets=$('challengePresets');if(presets){presets.replaceChildren();for(const value of config.presets){const button=document.createElement('button');button.type='button';button.textContent=`${value.toLocaleString(I18n.locale())}${config.unit}`;button.onclick=()=>{target.value=value;target.dataset.changed='1';[...presets.children].forEach(item=>item.classList.toggle('active',item===button));};presets.append(button);}}}
  async function createChallenge(){const friend=$('challengeFriend').value,metric=$('challengeMetric').value,days=+$('challengeDuration').value,config=metricSettings[metric]||metricSettings.workouts,target=Math.max(1,Math.min(config.max,Math.round(+$('challengeTarget').value||config.default)));if(!friend){toast(t('Wähle zuerst einen Freund.'));return;}try{await ForgeCloud.social('create_challenge',{friend,value:target,payload:{metric,days}});challengeFilter='invites';toggleComposer(false);await refreshChallenges();toast(t('Challenge gesendet.'));}catch(error){toast(error.message.includes('duplicate')?t('Mit diesem Freund gibt es bereits dieselbe Challenge für diesen Zeitraum.'):error.message);}}
  function challengeProgress(challenge){const start=new Date(`${challenge.starts_on}T00:00:00`),end=new Date(`${challenge.ends_on}T23:59:59.999`),logs=data.logs.filter(log=>{const date=new Date(log.date);return date>=start&&date<=end;});if(challenge.metric==='workouts')return logs.length;if(challenge.metric==='sets')return Math.round(logs.reduce((sum,log)=>sum+(Number(log.sets)||0),0));if(challenge.metric==='minutes')return Math.round(logs.reduce((sum,log)=>sum+(Number(log.minutes)||0),0));if(challenge.metric==='calories')return Math.round(logs.reduce((sum,log)=>sum+(Number(log.calories)||0),0));return Math.round(logs.reduce((sum,log)=>sum+(log.entries||[]).reduce((total,entry)=>total+(Number(entry.weight)||0)*(Number(entry.reps)||0),0),0));}
  async function syncProgress(challenges){if(!ForgeCloud.isSignedIn())return;const list=challenges||await ForgeCloud.social('challenges');for(const challenge of list.filter(item=>item.status==='accepted')){try{await ForgeCloud.social('sync_challenge',{id:challenge.id,value:challengeProgress(challenge)});}catch(error){}}}
  const formatDate=value=>new Date(`${value}T12:00:00`).toLocaleDateString(I18n.locale(),{day:'2-digit',month:'2-digit',year:'numeric'});
  function metricText(challenge){const config=metricSettings[challenge.metric]||metricSettings.workouts;return `${t(config.label)} · ${Number(challenge.target).toLocaleString(I18n.locale())}${config.unit}`;}
  function resultText(challenge){const a=Number(challenge.creator_progress),b=Number(challenge.opponent_progress);if(a===b)return t('Unentschieden');return `${a>b?challenge.creator_name:challenge.opponent_name} ${t('hat gewonnen!')}`;}
  async function refreshChallenges(){
    const list=$('challengesList');if(!list||!ForgeCloud.isSignedIn())return;
    try{
      let challenges=await ForgeCloud.social('challenges');await syncProgress(challenges);challenges=await ForgeCloud.social('challenges');
      const today=new Date();today.setHours(0,0,0,0);const isFinished=c=>c.status==='accepted'&&today>new Date(`${c.ends_on}T23:59:59`);
      const groups={active:challenges.filter(c=>c.status==='accepted'&&!isFinished(c)),invites:challenges.filter(c=>c.status==='pending'),history:challenges.filter(isFinished)};
      $('activeChallengeCount').textContent=groups.active.length;document.querySelectorAll('#challengeFilter button').forEach(button=>button.classList.toggle('active',button.dataset.filter===challengeFilter));
      list.replaceChildren();const visible=groups[challengeFilter];
      if(!visible.length){const empty=document.createElement('div');empty.className='social-empty';empty.innerHTML=`<span>${challengeFilter==='active'?'⚔️':challengeFilter==='invites'?'✉️':'🏁'}</span><b>${t(challengeFilter==='active'?'Keine aktive Challenge':'Hier ist noch nichts')}</b><small>${t(challengeFilter==='active'?'Starte eine Challenge und bleibt gemeinsam dran.':'Dieser Bereich füllt sich automatisch.')}</small>`;list.append(empty);return;}
      for(const c of visible){
        const card=document.createElement('div'),end=new Date(`${c.ends_on}T23:59:59`),finished=isFinished(c),opponent=c.incoming?c.creator_name:c.opponent_name;card.className=`challenge-card${finished?' finished':''}`;
        const head=document.createElement('div');head.className='challenge-head';head.innerHTML=`<span class="friend-avatar">${escapeHtml(opponent.slice(0,1).toUpperCase())}</span><div><small>${t(c.status==='pending'?(c.incoming?'Neue Einladung':'Einladung gesendet'):'Du gegen')}</small><b>${escapeHtml(opponent)}</b></div><strong>${escapeHtml(metricText(c))}</strong>`;card.append(head);
        const meta=document.createElement('div');meta.className='challenge-meta';for(const value of [`${formatDate(c.starts_on)} – ${formatDate(c.ends_on)}`,c.status==='pending'?t('Wartet auf Annahme'):`${Math.max(0,Math.ceil((end-today)/86400000))} ${t('Tage verbleibend')}`]){const tag=document.createElement('span');tag.className='tag';tag.textContent=value;meta.append(tag);}card.append(meta);
        if(c.status==='pending'){
          const actions=document.createElement('div');actions.className='account-buttons';if(c.incoming){const accept=document.createElement('button');accept.className='btn';accept.textContent=t('Annehmen');accept.onclick=()=>challengeAction('accept_challenge',c.id);actions.append(accept);}const remove=document.createElement('button');remove.className='btn secondary';remove.textContent=c.incoming?t('Ablehnen'):t('Zurückziehen');remove.onclick=()=>challengeAction('remove_challenge',c.id);actions.append(remove);card.append(actions);
        }else{
          const config=metricSettings[c.metric]||metricSettings.workouts;for(const [name,value] of [[c.creator_name,c.creator_progress],[c.opponent_name,c.opponent_progress]]){const row=document.createElement('div');row.className='challenge-progress';const label=document.createElement('span'),score=document.createElement('b'),bar=document.createElement('i');label.textContent=name;score.textContent=`${Number(value).toLocaleString(I18n.locale())} / ${Number(c.target).toLocaleString(I18n.locale())}${config.unit}`;bar.style.width=`${Math.min(100,Number(value)/Number(c.target)*100)}%`;row.append(label,score,bar);card.append(row);}const info=document.createElement('div');info.className=finished?'challenge-result':'challenge-live';info.textContent=finished?`🏆 ${resultText(c)}`:`● ${t('Live-Fortschritt')}`;card.append(info);const remove=document.createElement('button');remove.className='btn secondary challenge-remove';remove.textContent=finished?t('Aus Verlauf entfernen'):t('Challenge beenden');remove.onclick=()=>challengeAction('remove_challenge',c.id);card.append(remove);
        }list.append(card);
      }
    }catch(error){list.textContent=error.message;}
  }
  async function challengeAction(action,id){try{await ForgeCloud.social(action,{id});await refreshChallenges();}catch(error){toast(error.message);}}
  async function refreshAccount(){if(!ForgeCloud.isSignedIn())return;await refreshFriendsPage();}
  function init(){$('sharePlanSend').onclick=sendShare;$('challengeCreate').onclick=createChallenge;$('challengeMetric').onchange=()=>{delete $('challengeTarget').dataset.changed;updateChallengeDefaults();};$('challengeTarget').oninput=()=>{$('challengeTarget').dataset.changed='1';};document.querySelectorAll('#challengeFilter button').forEach(button=>button.onclick=()=>{challengeFilter=button.dataset.filter;refreshChallenges();});updateChallengeDefaults();window.addEventListener('forge-language-change',()=>{updateChallengeDefaults();if(!$('friends').classList.contains('hidden'))refreshFriendsPage();});}
  return {init,openShare,closeShare,refreshShares,refreshAccount,refreshFriendsPage,refreshChallenges,syncProgress,switchView,toggleComposer,challengeFriendName};
})();
